import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from './helpers/verified_app.js';
import {emptyData} from '../src/validation.js';
async function fixture(t){const f=await createApp({databasePath:':memory:',worker:false,env:{},now:()=>Date.parse('2026-10-01T00:00:00Z')});t.after(()=>f.app.close());const r=await f.app.inject({method:'POST',url:'/api/v1/auth/register',payload:{email:'a@example.com',password:'long-password-123',displayName:'A'}});const headers={authorization:'Bearer '+r.json().token};const call=(method,path,payload)=>f.app.inject({method,url:'/api/v1'+path,payload,headers});return {...f,call};}
test('schedule has three non-writing candidates, selected blocks apply once and undo safely',async t=>{
 const f=await fixture(t),data=emptyData();data.tasks=[{id:'t',title:'Task',estimateMinutes:60}];data.events=[{id:'busy',title:'Locked',start:'2026-10-01T09:00:00Z',end:'2026-10-01T10:00:00Z',locked:true}];await f.call('PUT','/workspace',{baseVersion:0,data});
 const p=await f.call('POST','/ai/schedule',{taskIds:['t'],start:'2026-10-01T09:00:00Z',end:'2026-10-02T18:00:00Z',timezone:'UTC'});assert.equal(p.statusCode,200,p.body);assert.equal(p.json().candidates.length,3);assert.equal((await f.call('GET','/workspace')).json().version,1);
 for(const c of p.json().candidates)assert.ok(Date.parse(c.intent.actions[0].start)>=Date.parse(data.events[0].end));
 const a=await f.call('POST','/ai/apply',{previewId:p.json().previewId,candidateId:p.json().candidates[0].id,baseVersion:1});assert.equal(a.statusCode,200,a.body);assert.equal((await f.call('GET','/workspace')).json().data.events.length,2);
 const audit=(await f.call('GET','/audit')).json().records.find(v=>v.action==='ai.apply');assert.ok(audit.reversible);const undo=await f.call('POST',`/audit/${audit.id}/undo`,{baseVersion:2});assert.equal(undo.statusCode,200,undo.body);assert.equal((await f.call('GET','/workspace')).json().data.events.length,1);
});
test('schedule refuses locked replan and impossible deadlines',async t=>{const f=await fixture(t),d=emptyData();d.tasks=[{id:'t',title:'Task',estimateMinutes:60,deadline:'2026-10-01T09:20:00Z'}];await f.call('PUT','/workspace',{baseVersion:0,data:d});const p=await f.call('POST','/ai/schedule',{taskIds:['t'],start:'2026-10-01T09:00:00Z',end:'2026-10-01T12:00:00Z',timezone:'UTC'});assert.equal(p.statusCode,422,p.body);});
test('stale candidates cannot overwrite edits and undo refuses later object changes',async t=>{const f=await fixture(t),d=emptyData();d.tasks=[{id:'t',title:'Task',estimateMinutes:60}];await f.call('PUT','/workspace',{baseVersion:0,data:d});let p=(await f.call('POST','/ai/schedule',{taskIds:['t'],start:'2026-10-01T09:00:00Z',end:'2026-10-01T18:00:00Z',timezone:'UTC'})).json();await f.call('PUT','/workspace',{baseVersion:1,data:d});assert.equal((await f.call('POST','/ai/apply',{previewId:p.previewId,candidateId:'0',baseVersion:2})).statusCode,409);p=(await f.call('POST','/ai/schedule',{taskIds:['t'],start:'2026-10-01T09:00:00Z',end:'2026-10-01T18:00:00Z',timezone:'UTC'})).json();const a=(await f.call('POST','/ai/apply',{previewId:p.previewId,candidateId:'0',baseVersion:2})).json();const w=(await f.call('GET','/workspace')).json();w.data.events[0].title='Edited';await f.call('PUT','/workspace',{baseVersion:3,data:w.data});assert.equal((await f.call('POST',`/audit/${a.auditId}/undo`,{baseVersion:4})).statusCode,409);});
test('AI reminder intent applies queue transactionally and audit undo removes it',async t=>{const f=await fixture(t),user=f.db.prepare('SELECT id FROM users').get();f.db.prepare('INSERT INTO previews VALUES(?,?,?,?,NULL)').run('reminder-preview',user.id,Date.parse('2026-10-01T00:15:00Z'),JSON.stringify({actions:[{type:'reminder',title:'Review',dueAt:'2026-10-02T09:00:00Z',strong:true,intervalMinutes:10,maxReminders:4}]}));const applied=await f.call('POST','/ai/apply',{previewId:'reminder-preview',baseVersion:0});assert.equal(applied.statusCode,200,applied.body);const reminders=(await f.call('GET','/reminders')).json().reminders;assert.equal(reminders.length,1);assert.equal(reminders[0].intervalMinutes,10);const undone=await f.call('POST',`/audit/${applied.json().auditId}/undo`,{baseVersion:1});assert.equal(undone.statusCode,200,undone.body);assert.equal((await f.call('GET','/reminders')).json().reminders.length,0);});
test('AI updates one event reminder without deleting sibling rules and undo restores it',async t=>{const f=await fixture(t),data=emptyData();data.events=[{id:'e',title:'Meeting',start:'2026-10-01T09:00:00Z',end:'2026-10-01T10:00:00Z',reminderRules:[{leadMinutes:5},{leadMinutes:30}]}];await f.call('PUT','/workspace',{baseVersion:0,data});const before=(await f.call('GET','/reminders')).json().reminders,user=f.db.prepare('SELECT id FROM users').get();f.db.prepare('INSERT INTO previews VALUES(?,?,?,?,NULL)').run('edit-reminder',user.id,Date.parse('2026-10-01T00:15:00Z'),JSON.stringify({actions:[{type:'reminder_update',id:before[0].id,strong:true,maxReminders:4}]}));const applied=await f.call('POST','/ai/apply',{previewId:'edit-reminder',baseVersion:1});assert.equal(applied.statusCode,200,applied.body);let rows=(await f.call('GET','/reminders')).json().reminders;assert.equal(rows.length,2);assert.ok(rows.some(r=>r.id===before[1].id));assert.equal(rows.find(r=>r.id===before[0].id).strong,true);const undone=await f.call('POST',`/audit/${applied.json().auditId}/undo`,{baseVersion:2});assert.equal(undone.statusCode,200,undone.body);rows=(await f.call('GET','/reminders')).json().reminders;assert.equal(rows.length,2);assert.equal(rows.find(r=>r.id===before[0].id).strong,false);});
