import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from './helpers/verified_app.js';
import {emptyData} from '../src/validation.js';
async function fixture(t){const dir=mkdtempSync(join(tmpdir(),'flowday-test-'));let time=Date.parse('2026-09-29T10:00:00Z');const ctx=await createApp({databasePath:join(dir,'test.sqlite'),worker:false,env:{},now:()=>time});t.after(async()=>{await ctx.app.close();rmSync(dir,{recursive:true,force:true});});const call=(method,url,body,token)=>ctx.app.inject({method,url:'/api/v1'+url,payload:body,headers:token?{authorization:'Bearer '+token}:{}});const register=async(email)=>{const r=await call('POST','/auth/register',{email,password:'good-password-123',displayName:'Test'});assert.equal(r.statusCode,201,r.body);return r.json();};return {...ctx,call,register,advance:ms=>{time+=ms;}};}
test('auth sessions, expiry and cross-user workspace isolation',async t=>{const f=await fixture(t);const a=await f.register('a@example.com'),b=await f.register('b@example.com');assert.equal((await f.call('GET','/workspace')).statusCode,401);const data=emptyData();data.tasks.push({id:'task-a',title:'Private'});assert.equal((await f.call('PUT','/workspace',{baseVersion:0,data},a.token)).statusCode,200);assert.deepEqual((await f.call('GET','/workspace',undefined,b.token)).json().data.tasks,[]);assert.equal((await f.call('POST','/auth/login',{email:'a@example.com',password:'wrong'})).statusCode,401);assert.equal((await f.call('POST','/auth/logout',{},a.token)).statusCode,204);assert.equal((await f.call('GET','/auth/me',undefined,a.token)).statusCode,401);f.advance(31*86400000);assert.equal((await f.call('GET','/workspace',undefined,b.token)).statusCode,401);});
test('schema, ownership input and compare-and-swap prevent invalid writes',async t=>{const f=await fixture(t),a=await f.register('a@example.com');const data=emptyData();const invalid=structuredClone(data);invalid.events=[{id:'e',title:'Invalid',start:'2026-09-29T10:00:00Z',end:'2026-09-29T09:00:00Z'}];assert.equal((await f.call('PUT','/workspace',{baseVersion:0,data:invalid},a.token)).statusCode,400);invalid.events=[];invalid.tasks=[{id:'a',title:'a',parentId:'b'},{id:'b',title:'b',parentId:'a'}];assert.equal((await f.call('PUT','/workspace',{baseVersion:0,data:invalid},a.token)).statusCode,400);invalid.tasks=[];invalid.preferences={apiKey:'not-allowed'};assert.equal((await f.call('PUT','/workspace',{baseVersion:0,data:invalid},a.token)).statusCode,400);const responses=await Promise.all([f.call('PUT','/workspace',{baseVersion:0,data},a.token),f.call('PUT','/workspace',{baseVersion:0,data},a.token)]);assert.deepEqual(responses.map(r=>r.statusCode).sort(),[200,409]);assert.equal(responses.find(r=>r.statusCode===409).json().currentVersion,1);assert.equal((await f.call('PUT','/workspace',{baseVersion:1,data,userId:'other'},a.token)).statusCode,400);});
test('backup restore is owned, transactional and creates a protection copy',async t=>{const f=await fixture(t),a=await f.register('a@example.com'),b=await f.register('b@example.com');const backup=(await f.call('POST','/backups',{},a.token)).json();assert.equal((await f.call('POST',`/backups/${backup.id}/restore`,{baseVersion:0},b.token)).statusCode,404);const data=emptyData();data.tasks=[{id:'a',title:'Later'}];await f.call('PUT','/workspace',{baseVersion:0,data},a.token);assert.equal((await f.call('POST',`/backups/${backup.id}/restore`,{baseVersion:0},a.token)).statusCode,409);assert.equal((await f.call('GET','/backups',undefined,a.token)).json().backups.length,1);const restored=await f.call('POST',`/backups/${backup.id}/restore`,{baseVersion:1},a.token);assert.equal(restored.statusCode,200,restored.body);assert.equal(restored.json().version,2);assert.equal((await f.call('GET','/workspace',undefined,a.token)).json().data.tasks.length,0);assert.equal((await f.call('GET','/backups',undefined,a.token)).json().backups.length,2);});
test('persistent worker fires without clients, reading notice does not ack strong reminders',async t=>{const f=await fixture(t),a=await f.register('a@example.com'),b=await f.register('b@example.com');const r=(await f.call('POST','/reminders',{dueAt:'2026-09-29T10:00:00Z',title:'Reminder',strong:true,intervalMinutes:1,maxReminders:3},a.token)).json().reminder;await f.runWorker();let w=(await f.call('GET','/workspace',undefined,a.token)).json();assert.equal(w.version,1);assert.equal(w.data.notices.length,1);w.data.notices[0].read=true;await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data},a.token);f.advance(60000);await f.runWorker();assert.equal((await f.call('GET','/workspace',undefined,a.token)).json().data.notices.length,2);assert.equal((await f.call('POST',`/reminders/${r.id}/ack`,{},b.token)).statusCode,404);assert.equal((await f.call('POST',`/reminders/${r.id}/ack`,{},a.token)).statusCode,200);f.advance(60000);await f.runWorker();assert.equal((await f.call('GET','/workspace',undefined,a.token)).json().data.notices.length,2);assert.equal((await f.call('GET','/backups',undefined,a.token)).json().backups[0].reason,'daily');});
test('unconfigured integrations return errors without changing workspace',async t=>{const f=await fixture(t),a=await f.register('a@example.com');const ai=await f.call('POST','/ai/preview',{text:'明天开会',timezone:'Asia/Shanghai'},a.token);assert.equal(ai.statusCode,503);assert.equal(ai.json().error.code,'AI_NOT_CONFIGURED');assert.equal((await f.call('POST','/reminders',{dueAt:'2026-09-29T10:00:00Z',title:'Test',channel:'feishu'},a.token)).statusCode,503);assert.equal((await f.call('GET','/workspace',undefined,a.token)).json().version,0);});
test('AI applies server snapshot once and preserves ownership',async t=>{const f=await fixture(t),a=await f.register('a@example.com'),b=await f.register('b@example.com');f.db.prepare('INSERT INTO previews VALUES(?,?,?,?,NULL)').run('preview',a.user.id,Date.parse('2026-09-29T10:15:00Z'),JSON.stringify({actions:[{type:'todo',title:'From AI'}]}));assert.equal((await f.call('POST','/ai/apply',{previewId:'preview',baseVersion:0},b.token)).statusCode,404);assert.equal((await f.call('POST','/ai/apply',{previewId:'preview',baseVersion:0},a.token)).statusCode,200);assert.equal((await f.call('POST','/ai/apply',{previewId:'preview',baseVersion:0},a.token)).statusCode,200);assert.equal((await f.call('GET','/workspace',undefined,a.token)).json().data.tasks.length,1);});
test('restart retains auth and reminder queue without a client connection',async()=>{
  const dir=mkdtempSync(join(tmpdir(),'flowday-restart-')),path=join(dir,'test.sqlite');let ctx;
  try {ctx=await createApp({databasePath:path,worker:false,env:{}});const registered=await ctx.app.inject({method:'POST',url:'/api/v1/auth/register',payload:{email:'restart@example.com',password:'long-password-123',displayName:'Test'}});const token=registered.json().token;const headers={authorization:'Bearer '+token};await ctx.app.inject({method:'POST',url:'/api/v1/reminders',headers,payload:{title:'Persistent',dueAt:new Date(Date.now()-1000).toISOString()}});await ctx.app.close();ctx=await createApp({databasePath:path,worker:false,env:{}});await ctx.runWorker();const workspace=await ctx.app.inject({method:'GET',url:'/api/v1/workspace',headers});assert.equal(workspace.statusCode,200);assert.equal(workspace.json().data.notices[0].title,'Persistent');}finally{if(ctx)await ctx.app.close();rmSync(dir,{recursive:true,force:true});}
});
test('daily trash purge keeps referenced objects and backs up before deletion',async t=>{
  const f=await fixture(t),a=await f.register('a@example.com'),data=emptyData();const deletedAt='2026-07-01T00:00:00Z';
  data.tasks=[{id:'unreferenced',title:'Remove',deletedAt},{id:'referenced',title:'Keep',deletedAt}];data.notices=[{id:'n',title:'Ref',body:'Ref',createdAt:deletedAt,taskId:'referenced'}];await f.call('PUT','/workspace',{baseVersion:0,data},a.token);await f.runWorker();const w=(await f.call('GET','/workspace',undefined,a.token)).json();assert.deepEqual(w.data.tasks.map(v=>v.id),['referenced']);assert.equal(w.version,2);const backup=f.db.prepare('SELECT data FROM backups WHERE user_id=?').get(a.user.id);assert.equal(JSON.parse(backup.data).tasks.length,2);
});
