import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from './helpers/verified_app.js';
const origin='https://caldav.icloud.com',calendarUrl=origin+'/cal/work/';
const ics=(title='Remote',start='20261002T090000Z',extra='')=>`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Test//EN\r\nBEGIN:VEVENT\r\nUID:remote-1\r\nSUMMARY:${title}\r\nDTSTART:${start}\r\nDTEND:20261002T100000Z\r\n${extra}END:VEVENT\r\nEND:VCALENDAR\r\n`;
const xmlEscape=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function mockDav(){const objects=new Map([[calendarUrl+'remote.ics',{data:ics(),etag:'"1"'}]]),requests=[];let sequence=1,fail=false;
 const response=entries=>new Response(`<?xml version="1.0"?><d:multistatus xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">${entries.map(([href,props])=>`<d:response><d:href>${xmlEscape(href)}</d:href><d:propstat><d:prop>${props}</d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response>`).join('')}</d:multistatus>`,{status:207,headers:{'Content-Type':'application/xml'}});
 const fetch=async(url,options={})=>{url=String(url);const method=options.method??'GET',body=String(options.body??'');requests.push({url,method,body,headers:options.headers});if(fail)return new Response('',{status:503});const path=new URL(url).pathname;
  if(path==='/.well-known/caldav')return new Response(null,{status:301,headers:{Location:origin+'/'}});
  if(method==='PROPFIND'){
   if(path==='/')return response([['/','<d:current-user-principal><d:href>/principal/</d:href></d:current-user-principal>']]);
   if(path==='/principal/')return response([['/principal/','<c:calendar-home-set><d:href>/cal/</d:href></c:calendar-home-set>']]);
   if(path==='/cal/')return response([['/cal/work/','<d:displayname>Work</d:displayname><d:resourcetype><d:collection/><c:calendar/></d:resourcetype><c:supported-calendar-component-set><c:comp name="VEVENT"/></c:supported-calendar-component-set>']]);
   return response([['/cal/work/','<d:supported-report-set><d:supported-report><d:report><c:calendar-query/></d:report></d:supported-report></d:supported-report-set>']]);
  }
  if(method==='REPORT')return response([...objects].map(([u,v])=>[new URL(u).pathname,`<d:getetag>${xmlEscape(v.etag)}</d:getetag>${body.includes('calendar-multiget')?`<c:calendar-data><![CDATA[${v.data}]]></c:calendar-data>`:''}`]));
  if(method==='GET'){const o=objects.get(url);return o?new Response(o.data,{status:200,headers:{ETag:o.etag}}):new Response('',{status:404});}
  if(method==='PUT'){const current=objects.get(url),headers=new Headers(options.headers);if(headers.get('if-match')&&headers.get('if-match')!==current?.etag)return new Response('',{status:412});if(headers.get('if-none-match')==='*'&&current)return new Response('',{status:412});const etag='"'+(++sequence)+'"';objects.set(url,{data:body,etag});return new Response(null,{status:current?204:201,headers:{ETag:etag}});}
  if(method==='DELETE'){objects.delete(url);return new Response(null,{status:204});}throw new Error('Unhandled mock DAV request');
 };return {objects,requests,fetch,setFail:v=>{fail=v;},change:data=>{objects.set(calendarUrl+'remote.ics',{data,etag:'"'+(++sequence)+'"'});}};
}
async function fixture(t){const remote=mockDav(),f=await createApp({databasePath:':memory:',worker:false,env:{INTEGRATION_ENCRYPTION_KEY:'ab'.repeat(32)},caldavFetch:remote.fetch,now:()=>Date.parse('2026-10-01T00:00:00Z')});t.after(()=>f.app.close());const register=async email=>(await f.app.inject({method:'POST',url:'/api/v1/auth/register',payload:{email,password:'long-test-password-123',displayName:'Test'}})).json();const a=await register('a@example.com'),b=await register('b@example.com');const call=(method,path,payload,token=a.token)=>f.app.inject({method,url:'/api/v1'+path,payload,headers:{authorization:'Bearer '+token}});const credentials={username:'test@example.com',password:'test-app-password',calendarUrl};return {...f,remote,a,b,call,credentials};}
test('CalDAV discovers calendars, encrypts credentials and imports locked idempotent events',async t=>{const f=await fixture(t);const discovery=await f.call('POST','/integrations/apple/discover',{username:f.credentials.username,password:f.credentials.password});assert.equal(discovery.statusCode,200,discovery.body);assert.equal(discovery.json().calendars[0].url,calendarUrl);const connect=await f.call('PUT','/integrations/apple',f.credentials);assert.equal(connect.statusCode,200,connect.body);assert.ok(!connect.body.includes(f.credentials.password));assert.ok(!JSON.stringify(f.db.prepare('SELECT * FROM calendar_connections').all()).includes(f.credentials.password));assert.equal((await f.call('POST','/integrations/apple/sync',{})).statusCode,200);let w=(await f.call('GET','/workspace')).json();assert.equal(w.data.events.length,1);assert.equal(w.data.events[0].locked,true);assert.equal((await f.call('POST','/integrations/apple/sync',{})).statusCode,200);assert.equal((await f.call('GET','/workspace')).json().data.events.length,1);assert.equal((await f.call('GET','/integrations/apple',undefined,f.b.token)).json().configured,false);});
test('CalDAV pushes local changes, reports two-sided conflicts and resolves remote choice',async t=>{const f=await fixture(t);await f.call('PUT','/integrations/apple',f.credentials);await f.call('POST','/integrations/apple/sync',{});let w=(await f.call('GET','/workspace')).json();w.data.events[0].title='Local changed';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});const pushed=await f.call('POST','/integrations/apple/sync',{});assert.equal(pushed.statusCode,200,pushed.body);assert.match(f.remote.objects.get(calendarUrl+'remote.ics').data,/SUMMARY:Local changed/);
 w=(await f.call('GET','/workspace')).json();w.data.events[0].title='Later local';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});f.remote.change(ics('Later remote'));const sync=await f.call('POST','/integrations/apple/sync',{});assert.equal(sync.statusCode,200,sync.body);assert.equal(sync.json().conflicts,1);const state=(await f.call('GET','/integrations/apple')).json();assert.equal(state.conflicts.length,1);w=(await f.call('GET','/workspace')).json();assert.equal(w.data.events[0].title,'Later local');const resolve=await f.call('POST',`/integrations/apple/conflicts/${state.conflicts[0].id}/resolve`,{choice:'remote',baseVersion:w.version});assert.equal(resolve.statusCode,200,resolve.body);assert.equal((await f.call('GET','/workspace')).json().data.events[0].title,'Later remote');});
test('CalDAV remote deletion trashes local, local deletion deletes remote and failures preserve state',async t=>{const f=await fixture(t);await f.call('PUT','/integrations/apple',f.credentials);await f.call('POST','/integrations/apple/sync',{});f.remote.objects.clear();const sync=await f.call('POST','/integrations/apple/sync',{});assert.equal(sync.statusCode,200,sync.body);let w=(await f.call('GET','/workspace')).json();assert.ok(w.data.events[0].deletedAt);w.data.events.push({id:'local',title:'Local new',start:'2026-10-02T12:00:00Z',end:'2026-10-02T13:00:00Z'});await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});assert.equal((await f.call('POST','/integrations/apple/sync',{})).statusCode,200);assert.equal(f.remote.objects.size,1);w=(await f.call('GET','/workspace')).json();w.data.events.find(e=>e.id==='local').deletedAt='2026-10-01T00:00:00Z';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});await f.call('POST','/integrations/apple/sync',{});assert.equal(f.remote.objects.size,0);f.remote.setFail(true);const before=(await f.call('GET','/workspace')).json();assert.equal((await f.call('POST','/integrations/apple/sync',{})).statusCode,502);assert.deepEqual((await f.call('GET','/workspace')).json(),before);assert.equal((await f.call('GET','/integrations/apple')).json().lastError,'CALDAV_SYNC_FAILED');});
test('CalDAV recurrence edits preserve master and single-instance deletion writes EXDATE',async t=>{const f=await fixture(t);f.remote.change(ics('Weekly','20261002T090000Z','RRULE:FREQ=WEEKLY;COUNT=3\r\nX-KEEP:preserved\r\n'));await f.call('PUT','/integrations/apple',f.credentials);let response=await f.call('POST','/integrations/apple/sync',{});assert.equal(response.statusCode,200,response.body);let w=(await f.call('GET','/workspace')).json();assert.equal(w.data.events.length,3);w.data.events[1].title='Exception';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});response=await f.call('POST','/integrations/apple/sync',{});assert.equal(response.statusCode,200,response.body);assert.match(f.remote.objects.get(calendarUrl+'remote.ics').data,/RECURRENCE-ID:20261009T090000Z/);assert.match(f.remote.objects.get(calendarUrl+'remote.ics').data,/X-KEEP:preserved/);response=await f.call('POST','/integrations/apple/sync',{});assert.equal(response.statusCode,200,response.body);w=(await f.call('GET','/workspace')).json();assert.equal(w.data.events.length,3);assert.equal(w.data.events[1].title,'Exception');w.data.events[2].deletedAt='2026-10-01T00:00:00Z';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});response=await f.call('POST','/integrations/apple/sync',{});assert.equal(response.statusCode,200,response.body);assert.match(f.remote.objects.get(calendarUrl+'remote.ics').data,/EXDATE:20261016T090000Z/);await f.call('POST','/integrations/apple/sync',{});assert.equal((await f.call('GET','/workspace')).json().data.events.filter(e=>!e.deletedAt).length,2);});
test('local-choice conflict restores the same remote URL and account deletion clears encrypted connections',async t=>{const f=await fixture(t);await f.call('PUT','/integrations/apple',f.credentials);await f.call('POST','/integrations/apple/sync',{});let w=(await f.call('GET','/workspace')).json();w.data.events[0].title='Keep local';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});f.remote.objects.clear();await f.call('POST','/integrations/apple/sync',{});const state=(await f.call('GET','/integrations/apple')).json();w=(await f.call('GET','/workspace')).json();const r=await f.call('POST',`/integrations/apple/conflicts/${state.conflicts[0].id}/resolve`,{choice:'local',baseVersion:w.version});assert.equal(r.statusCode,200,r.body);assert.ok(f.remote.objects.has(calendarUrl+'remote.ics'));assert.equal((await f.call('POST','/auth/delete',{password:'long-test-password-123',confirmation:'DELETE'})).statusCode,204);assert.equal(f.db.prepare('SELECT count(*) AS n FROM calendar_connections').get().n,0);});
test('CalDAV rejects unapproved hosts and refuses another user conflict resolution',async t=>{const f=await fixture(t);assert.equal((await f.call('POST','/integrations/apple/discover',{username:'test',password:'test',serverUrl:'https://127.0.0.1/'})).statusCode,400);await f.call('PUT','/integrations/apple',f.credentials);await f.call('POST','/integrations/apple/sync',{});let w=(await f.call('GET','/workspace')).json();w.data.events[0].title='Local';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});f.remote.change(ics('Remote conflict'));await f.call('POST','/integrations/apple/sync',{});const id=(await f.call('GET','/integrations/apple')).json().conflicts[0].id;assert.equal((await f.call('POST',`/integrations/apple/conflicts/${id}/resolve`,{choice:'remote',baseVersion:0},f.b.token)).statusCode,404);});
test('recurring local exports recover idempotently after lost response mapping',async t=>{const f=await fixture(t);await f.call('PUT','/integrations/apple',f.credentials);let w=(await f.call('GET','/workspace')).json();w.data.events=[{id:'local-series',title:'Local weekly',start:'2026-10-02T12:00:00Z',end:'2026-10-02T13:00:00Z',repeatRule:{frequency:'weekly',interval:1,count:3,until:null}}];await f.call('PUT','/workspace',{baseVersion:0,data:w.data});const first=await f.call('POST','/integrations/apple/sync',{});assert.equal(first.statusCode,200,first.body);f.db.prepare("DELETE FROM calendar_mappings WHERE source='local'").run();const retry=await f.call('POST','/integrations/apple/sync',{});assert.equal(retry.statusCode,200,retry.body);assert.equal((await f.call('GET','/workspace')).json().data.events.length,2);assert.equal(f.remote.objects.size,2);assert.equal(f.db.prepare('SELECT remote_key FROM calendar_mappings WHERE event_id=?').get('local-series').remote_key,'');const again=await f.call('POST','/integrations/apple/sync',{});assert.equal(again.statusCode,200,again.body);assert.equal((await f.call('GET','/workspace')).json().data.events.length,2);});
test('local choice restores a remote excluded recurrence within original series',async t=>{const f=await fixture(t);f.remote.change(ics('Weekly','20261002T090000Z','RRULE:FREQ=WEEKLY;COUNT=3\r\n'));await f.call('PUT','/integrations/apple',f.credentials);await f.call('POST','/integrations/apple/sync',{});let w=(await f.call('GET','/workspace')).json();w.data.events[1].title='Keep exception';await f.call('PUT','/workspace',{baseVersion:w.version,data:w.data});f.remote.change(ics('Weekly','20261002T090000Z','RRULE:FREQ=WEEKLY;COUNT=3\r\nEXDATE:20261009T090000Z\r\n'));await f.call('POST','/integrations/apple/sync',{});const state=(await f.call('GET','/integrations/apple')).json();w=(await f.call('GET','/workspace')).json();const resolved=await f.call('POST',`/integrations/apple/conflicts/${state.conflicts[0].id}/resolve`,{choice:'local',baseVersion:w.version});assert.equal(resolved.statusCode,200,resolved.body);assert.equal(f.remote.objects.size,1);assert.match(f.remote.objects.get(calendarUrl+'remote.ics').data,/SUMMARY:Keep exception/);});
