import {randomUUID} from 'node:crypto';
import {ApiError,check,object} from './validation.js';
import {applyIntent,scheduleCandidates} from './ai.js';
const text=v=>typeof v==='string'&&v.trim().length>0&&v.length<=2000;
const integer=v=>Number.isSafeInteger(v)&&v>=0;
export function registerAi({app,db,auth,now,env,workspace,tx,cas,audit,fetcher}){
 const reminders=uid=>db.prepare('SELECT * FROM reminders WHERE user_id=?').all(uid).map(r=>({id:r.id,taskId:r.task_id,eventId:r.event_id,ruleKey:r.rule_key,dueAt:new Date(r.due).toISOString(),intervalMinutes:r.interval_ms/60000,maxReminders:r.max_count,sentCount:r.sent,acknowledged:!!r.acknowledged,strong:!!r.strong,title:r.title,channel:r.channel,lastError:r.last_error}));
 const equalReminder=(a,b)=>a&&b?JSON.stringify(Object.keys(b).sort().map(k=>[k,a[k]]))===JSON.stringify(Object.keys(b).sort().map(k=>[k,b[k]])):a===b;
 const writeReminder=(uid,r)=>{if(r.channel==='feishu'&&!env.FEISHU_WEBHOOK_URL&&!db.prepare('SELECT user_id FROM integrations WHERE user_id=?').get(uid))throw new ApiError(503,'FEISHU_NOT_CONFIGURED','飞书提醒尚未配置');db.prepare('INSERT INTO reminders(id,user_id,task_id,event_id,rule_key,due,interval_ms,max_count,sent,acknowledged,strong,title,channel,last_error) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET task_id=excluded.task_id,event_id=excluded.event_id,rule_key=excluded.rule_key,due=excluded.due,interval_ms=excluded.interval_ms,max_count=excluded.max_count,sent=excluded.sent,acknowledged=excluded.acknowledged,strong=excluded.strong,title=excluded.title,channel=excluded.channel,last_error=excluded.last_error').run(r.id,uid,r.taskId??null,r.eventId??null,r.ruleKey??null,Date.parse(r.dueAt),r.intervalMinutes*60000,r.maxReminders,r.sentCount,Number(r.acknowledged),Number(r.strong),r.title,r.channel,r.lastError);};
 db.exec(`CREATE TABLE IF NOT EXISTS preview_details(id TEXT PRIMARY KEY REFERENCES previews(id) ON DELETE CASCADE,base_version INTEGER NOT NULL,input TEXT NOT NULL,candidates TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audit_changes(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),created INTEGER NOT NULL,action TEXT NOT NULL,before_data TEXT NOT NULL,after_data TEXT NOT NULL,version INTEGER NOT NULL,details TEXT NOT NULL,undone INTEGER NOT NULL DEFAULT 0);`);
 const store=(uid,input,w,candidates)=>{const id=randomUUID(),expires=now()+15*60000;tx(()=>{db.prepare('INSERT INTO previews VALUES(?,?,?,?,NULL)').run(id,uid,expires,JSON.stringify(candidates[0].intent));db.prepare('INSERT INTO preview_details VALUES(?,?,?,?)').run(id,w.version,input,JSON.stringify(candidates));});return {previewId:id,baseVersion:w.version,intent:candidates[0].intent,candidates,expiresAt:new Date(expires).toISOString()};};
 const config={preHandler:auth,config:{rateLimit:{max:20,timeWindow:'1 minute'}}};
 app.post('/api/v1/ai/schedule',config,async req=>{const w=workspace(req.uid);return store(req.uid,JSON.stringify(req.body),w,scheduleCandidates(w.data,req.body,now()));});
 app.post('/api/v1/ai/preview',config,async req=>{
  object(req.body,{text,timezone:v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return typeof v==='string';}catch{return false;}}},['text','timezone']);
  if(!env.AI_BASE_URL||!env.AI_API_KEY||!env.AI_MODEL)throw new ApiError(503,'AI_NOT_CONFIGURED','AI 服务尚未配置');
  const w=workspace(req.uid);let candidates;
  try{
   const response=await fetcher(env.AI_BASE_URL.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env.AI_API_KEY}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(30000),body:JSON.stringify({model:env.AI_MODEL,response_format:{type:'json_object'},messages:[{role:'system',content:'Return JSON {candidates:[{label,intent:{actions:[]}}]}. Return one candidate for clear input, exactly three for ambiguous times or target objects. Supported action types todo,event,todo_update,event_update,event_delete,reminder,reminder_update. Reminder fields title,dueAt,taskId,intervalMinutes,maxReminders,strong,channel (in_app or feishu). Reminder update requires existing id. Create fields: title,projectId; todo fields status,priority,estimateMinutes,deadline; event fields start,end,taskId,completed. Update/delete requires existing id. Dates ISO8601 with offset. Never modify locked, completed or started events, never create workflow nodes. Do not invent unrelated actions. Max 200 actions. Current time '+new Date(now()).toISOString()+', timezone '+req.body.timezone+'. Existing tasks/events/projects: '+JSON.stringify({tasks:w.data.tasks,events:w.data.events,projects:w.data.projects,reminders:reminders(req.uid)})},{role:'user',content:req.body.text}]})});
   if(!response.ok)throw new Error();const result=await response.json(),parsed=JSON.parse(result.choices[0].message.content),raw=parsed.candidates??[{label:'解析结果',intent:parsed}];
   check(Array.isArray(raw)&&[1,3].includes(raw.length));
   candidates=raw.map((c,i)=>{check(text(c.label));return {id:String(i),label:c.label,intent:c.intent,diff:applyIntent(w.data,c.intent,now(),reminders(req.uid)).diff};});
  }catch{throw new ApiError(502,'AI_INVALID_RESPONSE','AI 服务未返回有效预览');}
  return store(req.uid,req.body.text,w,candidates);
 });
 app.post('/api/v1/ai/apply',{preHandler:auth},async req=>{
  object(req.body,{previewId:text,baseVersion:integer,candidateId:text,actionIndexes:v=>Array.isArray(v)&&v.length>0&&v.every(integer)&&new Set(v).size===v.length},['previewId','baseVersion']);
  return tx(()=>{const p=db.prepare('SELECT * FROM previews WHERE id=? AND user_id=?').get(req.body.previewId,req.uid);if(!p)throw new ApiError(404,'NOT_FOUND','预览不存在');if(p.applied_version!==null)return {version:p.applied_version,applied:true};if(p.expires<=now())throw new ApiError(410,'PREVIEW_EXPIRED','预览已过期');
   const detail=db.prepare('SELECT * FROM preview_details WHERE id=?').get(p.id),w=workspace(req.uid);
   if(detail&&detail.base_version!==w.version)throw new ApiError(409,'PREVIEW_STALE','工作区已变化，请重新生成预览',{currentVersion:w.version});
   let intent=JSON.parse(p.intent);if(detail){const candidates=JSON.parse(detail.candidates);if(candidates.length>1)check(req.body.candidateId!==undefined,'请先选择候选方案');const chosen=candidates.find(c=>c.id===(req.body.candidateId??candidates[0].id));check(chosen,'候选不存在');for(const change of chosen.diff??[])if(change.collection==='reminders'&&change.before&&!equalReminder(reminders(req.uid).find(r=>r.id===change.id),change.before))throw new ApiError(409,'PREVIEW_STALE','提醒已变化，请重新生成预览');intent=chosen.intent;}
   if(req.body.actionIndexes){check(req.body.actionIndexes.every(i=>i<intent.actions.length));intent={actions:req.body.actionIndexes.map(i=>intent.actions[i])};}
   const applied=applyIntent(w.data,intent,now(),reminders(req.uid)),version=cas(req.uid,req.body.baseVersion,applied.data),auditId=randomUUID();
   for(const change of applied.diff.filter(d=>d.collection==='reminders'))writeReminder(req.uid,change.after);
   db.prepare('INSERT INTO audit_changes VALUES(?,?,?,?,?,?,?,?,0)').run(auditId,req.uid,now(),'ai.apply',JSON.stringify(w.data),JSON.stringify(applied.data),version,JSON.stringify({input:detail?.input??null,intent,diff:applied.diff,candidateId:req.body.candidateId??null}));
   db.prepare('UPDATE previews SET applied_version=? WHERE id=?').run(version,p.id);audit(req.uid,'ai.apply');return {version,applied:true,auditId};
  });
 });
 app.get('/api/v1/audit',{preHandler:auth},async req=>{const details=db.prepare('SELECT * FROM audit_changes WHERE user_id=? ORDER BY created DESC LIMIT 100').all(req.uid).map(r=>({id:r.id,action:r.action,createdAt:new Date(r.created).toISOString(),version:r.version,reversible:!r.undone,...JSON.parse(r.details)}));const basic=db.prepare("SELECT * FROM audit WHERE user_id=? AND action<>'ai.apply' ORDER BY created DESC LIMIT 100").all(req.uid).map(r=>({id:r.id,action:r.action,createdAt:new Date(r.created).toISOString(),reversible:false}));return {records:[...details,...basic].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,100)};});
 app.post('/api/v1/audit/:id/undo',{preHandler:auth},async req=>{object(req.body,{baseVersion:integer},['baseVersion']);return tx(()=>{const row=db.prepare('SELECT * FROM audit_changes WHERE id=? AND user_id=?').get(req.params.id,req.uid);if(!row)throw new ApiError(404,'NOT_FOUND','审计记录不存在');check(!row.undone,'操作已撤销');const w=workspace(req.uid),after=JSON.parse(row.after_data),before=JSON.parse(row.before_data),changes=JSON.parse(row.details).diff;
  for(const change of changes.filter((c,i)=>changes.findIndex(v=>v.id===c.id)===i)){if(change.collection==='reminders'){if(!equalReminder(reminders(req.uid).find(r=>r.id===change.id),change.after))throw new ApiError(409,'UNDO_CONFLICT','提醒已有后续修改，无法撤销');continue;}const key=change.type.startsWith('todo')?'tasks':'events',current=w.data[key].find(v=>v.id===change.id);if(JSON.stringify(current)!==JSON.stringify(after[key].find(v=>v.id===change.id)))throw new ApiError(409,'UNDO_CONFLICT','对象已有后续修改，无法撤销');const index=w.data[key].findIndex(v=>v.id===change.id),original=before[key].find(v=>v.id===change.id);if(original)w.data[key][index]=original;else w.data[key].splice(index,1);}
  const version=cas(req.uid,req.body.baseVersion,w.data);for(const change of changes.filter(d=>d.collection==='reminders')){if(change.before)writeReminder(req.uid,change.before);else db.prepare('DELETE FROM reminders WHERE id=? AND user_id=?').run(change.id,req.uid);}db.prepare('UPDATE audit_changes SET undone=1 WHERE id=?').run(row.id);audit(req.uid,'ai.undo');return {version,undone:true};});});
}

