import {DAVClient} from 'tsdav';
import {randomUUID} from 'node:crypto';
import {ApiError,check,object} from './validation.js';
import {credentialCodec} from './credentials.js';
import {eventFields,readCalendar,writeCalendar,sameEvent} from './ical.js';
const text=v=>typeof v==='string'&&v.trim().length>0&&v.length<=2000;
const integer=v=>Number.isSafeInteger(v)&&v>=0;
export function registerCalDav({app,db,auth,env,now,workspace,tx,cas,audit,fetcher=fetch}){
 db.exec(`CREATE TABLE IF NOT EXISTS calendar_connections(user_id TEXT PRIMARY KEY REFERENCES users(id),encrypted TEXT NOT NULL,calendar TEXT NOT NULL,last_sync INTEGER,last_attempt INTEGER,last_error TEXT);
 CREATE TABLE IF NOT EXISTS calendar_mappings(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),event_id TEXT NOT NULL,remote_url TEXT NOT NULL,remote_key TEXT NOT NULL,uid TEXT NOT NULL,source TEXT NOT NULL,etag TEXT,base_local TEXT NOT NULL,base_remote TEXT,status TEXT NOT NULL,last_sync INTEGER,UNIQUE(user_id,event_id),UNIQUE(user_id,remote_url,remote_key,uid));
 CREATE TABLE IF NOT EXISTS calendar_conflicts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),mapping_id TEXT NOT NULL REFERENCES calendar_mappings(id) ON DELETE CASCADE,event_id TEXT NOT NULL,local_data TEXT,remote_data TEXT,remote_etag TEXT,created INTEGER NOT NULL,resolved INTEGER NOT NULL DEFAULT 0);`);
 const codec=credentialCodec(env),active=new Set();
 const allowedUrl=value=>{try{const u=new URL(value),hosts=(env.CALDAV_ALLOWED_HOSTS??'').split(',').filter(Boolean);return u.protocol==='https:'&&!u.username&&!u.password&&!u.hash&&!u.search&&(!u.port||u.port==='443')&&(u.hostname==='caldav.icloud.com'||/^p\d+-caldav\.icloud\.com$/.test(u.hostname)||hosts.includes(u.hostname));}catch{return false;}};
 const safeFetch=async(url,init={})=>{check(allowedUrl(String(url)),'日历服务器地址未获允许');let response=await fetcher(String(url),{...init,redirect:'manual',signal:AbortSignal.timeout(20000)});if(response.status>=300&&response.status<400&&init.redirect!=='manual'){const next=new URL(response.headers.get('location'),String(url));check(allowedUrl(next.href),'日历重定向地址未获允许');response=await fetcher(next.href,{...init,redirect:'error',signal:AbortSignal.timeout(20000)});}return response;};
 const credentialsFields={username:v=>text(v)&&v.length<=254,password:v=>text(v)&&v.length<=256,serverUrl:allowedUrl};
 const client=async credentials=>{const c=new DAVClient({serverUrl:credentials.serverUrl??'https://caldav.icloud.com',credentials:{username:credentials.username,password:credentials.password},authMethod:'Basic',defaultAccountType:'caldav',fetch:safeFetch});await c.login();return c;};
 const connection=uid=>{const row=db.prepare('SELECT * FROM calendar_connections WHERE user_id=?').get(uid);if(!row)throw new ApiError(503,'APPLE_NOT_CONFIGURED','Apple 日历尚未连接');return {...row,credentials:codec.open(row.encrypted),selected:JSON.parse(row.calendar)};};
 const mappings=uid=>db.prepare('SELECT * FROM calendar_mappings WHERE user_id=?').all(uid);
 const conflictRows=uid=>db.prepare('SELECT * FROM calendar_conflicts WHERE user_id=? AND resolved=0 ORDER BY created DESC').all(uid);
 const status=uid=>{const c=db.prepare('SELECT calendar,last_sync,last_error FROM calendar_connections WHERE user_id=?').get(uid);if(!c)return {configured:false,records:[],conflicts:[]};const w=workspace(uid);return {configured:true,calendar:JSON.parse(c.calendar),lastSyncAt:c.last_sync?new Date(c.last_sync).toISOString():null,lastError:c.last_error,records:mappings(uid).map(row=>({eventId:row.event_id,source:row.source,status:row.status==='conflict'?'conflict':sameEvent(w.data.events.find(e=>e.id===row.event_id),JSON.parse(row.base_local))?'synced':'pending',lastSyncAt:row.last_sync?new Date(row.last_sync).toISOString():null,conflictId:conflictRows(uid).find(v=>v.mapping_id===row.id)?.id??null})),conflicts:conflictRows(uid).map(r=>({id:r.id,eventId:r.event_id,local:r.local_data?JSON.parse(r.local_data):null,remote:r.remote_data?JSON.parse(r.remote_data):null,remoteDeleted:!r.remote_data,createdAt:new Date(r.created).toISOString()}))};};
 const locked=uid=>{if(active.has(uid))throw new ApiError(409,'CALDAV_BUSY','日历同步正在执行');};
 const config={preHandler:auth,config:{rateLimit:{max:15,timeWindow:'1 minute'}}};
 app.get('/api/v1/integrations/apple',{preHandler:auth},async req=>status(req.uid));
 app.post('/api/v1/integrations/apple/discover',config,async req=>{object(req.body,credentialsFields,['username','password']);try{const c=await client(req.body),calendars=await c.fetchCalendars();return {calendars:calendars.filter(v=>!v.components?.length||v.components.includes('VEVENT')).map(v=>({url:v.url,displayName:v.displayName??''}))};}catch(e){if(e instanceof ApiError)throw e;throw new ApiError(502,'CALDAV_DISCOVERY_FAILED','无法发现日历，请检查账户和应用专用密码');}});
 app.put('/api/v1/integrations/apple',config,async req=>{object(req.body,{...credentialsFields,calendarUrl:allowedUrl},['username','password','calendarUrl']);locked(req.uid);active.add(req.uid);try{const c=await client(req.body),calendars=await c.fetchCalendars(),calendar=calendars.find(v=>v.url===req.body.calendarUrl);check(calendar,'所选日历不属于此账户');const old=db.prepare('SELECT calendar FROM calendar_connections WHERE user_id=?').get(req.uid);if(old&&JSON.parse(old.calendar).url!==calendar.url)throw new ApiError(409,'DISCONNECT_REQUIRED','请先断开原日历连接');db.prepare('INSERT INTO calendar_connections VALUES(?,?,?,NULL,NULL,NULL) ON CONFLICT(user_id) DO UPDATE SET encrypted=excluded.encrypted,calendar=excluded.calendar,last_error=NULL').run(req.uid,codec.seal(req.body),JSON.stringify({url:calendar.url,displayName:calendar.displayName??''}));audit(req.uid,'apple.connect');return status(req.uid);}catch(e){if(e instanceof ApiError)throw e;throw new ApiError(502,'CALDAV_DISCOVERY_FAILED','无法连接所选日历');}finally{active.delete(req.uid);}});
 const save=(uid,event,remote,source,old)=>{const id=old?.id??randomUUID();db.prepare('INSERT INTO calendar_mappings VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,event_id) DO UPDATE SET remote_url=excluded.remote_url,remote_key=excluded.remote_key,uid=excluded.uid,etag=excluded.etag,base_local=excluded.base_local,base_remote=excluded.base_remote,status=excluded.status,last_sync=excluded.last_sync').run(id,uid,event.id,remote.url,remote.key??'',remote.uid,source,remote.etag??null,JSON.stringify(event),remote.event?JSON.stringify(remote.event):null,'synced',now());db.prepare('UPDATE calendar_conflicts SET resolved=1 WHERE mapping_id=?').run(id);return id;};
 const markConflict=(uid,map,local,remote)=>tx(()=>{const old=db.prepare('SELECT id FROM calendar_conflicts WHERE mapping_id=? AND resolved=0').get(map.id),id=old?.id??randomUUID();db.prepare('INSERT INTO calendar_conflicts VALUES(?,?,?,?,?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET local_data=excluded.local_data,remote_data=excluded.remote_data,remote_etag=excluded.remote_etag').run(id,uid,map.id,map.event_id,local?JSON.stringify(local):null,remote?.event?JSON.stringify(remote.event):null,remote?.etag??null,now());db.prepare("UPDATE calendar_mappings SET status='conflict' WHERE id=?").run(map.id);if(!old){const w=workspace(uid),event=w.data.events.find(e=>e.id===map.event_id);w.data.notices.push({id:randomUUID(),title:'Apple 日历同步冲突',body:local?.title??remote?.event?.title??'',createdAt:new Date(now()).toISOString(),read:false,acknowledged:false,type:'calendar_conflict',eventId:event?.id??null,projectId:event?.projectId??null,taskId:event?.taskId??null,nodeId:null});cas(uid,w.version,w.data);audit(uid,'apple.conflict');}return id;});
 const pull=(uid,remote,map)=>tx(()=>{const w=workspace(uid);let event=w.data.events.find(e=>e.id===map?.event_id);if(!event){event={id:randomUUID(),locked:true};w.data.events.push(event);}if(remote.event){for(const [key,value] of Object.entries(remote.event))event[key]=value;delete event.deletedAt;}else event.deletedAt=new Date(now()).toISOString();const version=cas(uid,w.version,w.data);save(uid,event,remote,map?.source??'apple',map);audit(uid,remote.event?'apple.pull':'apple.delete');return version;});
 const checkResponse=response=>{if(response.status===412)throw new ApiError(409,'CALDAV_REMOTE_CHANGED','外部日程在同步中发生变化，请重新同步');if(!response.ok)throw new ApiError(502,'CALDAV_WRITE_FAILED','无法写入外部日历');};
 const push=async(uid,c,calendar,event,remote,map)=>{
  const detached=map?.remote_key&&!remote,externalUid=detached?`${event.id}@flowday.${uid}`:map?.uid??`${event.id}@flowday.${uid}`,url=detached?new URL('flowday-'+encodeURIComponent(event.id)+'.ics',calendar.url).href:map?.remote_url??new URL('flowday-'+encodeURIComponent(event.id)+'.ics',calendar.url).href,key=detached?'':map?.remote_key??'';let data=null,response;
  if(remote)check(typeof remote.etag==='string'&&remote.etag.length>0,'外部日程缺少版本标识，无法安全写入');
  if(event.deletedAt&&!key){response=await c.deleteCalendarObject({calendarObject:{url,etag:remote?.etag??map?.etag}});if(response.status!==404)checkResponse(response);}
  else {data=writeCalendar(event,{original:remote?.data,uid:externalUid,key,now:now()});response=map&&remote?await c.updateCalendarObject({calendarObject:{url,data,etag:remote.etag}}):await c.createCalendarObject({calendar,iCalString:data,filename:new URL(url).pathname.split('/').at(-1)});checkResponse(response);}
  const normalized={...eventFields(event)};delete normalized.deleted;
  tx(()=>{save(uid,event,{url,key,uid:externalUid,etag:response.headers.get('etag'),event:event.deletedAt?null:normalized},map?.source??'local',map);audit(uid,'apple.push');});
  return {url,data,etag:response.headers.get('etag')};
 };
 const loadRemote=async(uid,c,calendar)=>{const objects=await c.fetchCalendarObjects({calendar});check(objects.length<=10000,'外部日程数量超限');const maps=mappings(uid),remote=[];for(const object of objects){check(allowedUrl(object.url)&&object.url.startsWith(calendar.url),'外部日程地址无效');const forObject=maps.filter(m=>m.remote_url===object.url),events=readCalendar(object.data,{now:now(),timezone:workspace(uid).data.preferences.timezone??'UTC',wanted:forObject.map(m=>m.remote_key),keepSeries:forObject.some(m=>m.source==='local'&&m.remote_key==='')||workspace(uid).data.events.map(e=>e.id+'@flowday.'+uid)});for(const item of events)remote.push({...object,...item});}return {objects,remote};};
 async function sync(uid,eventIds){locked(uid);active.add(uid);db.prepare('UPDATE calendar_connections SET last_attempt=? WHERE user_id=?').run(now(),uid);const counts={imported:0,pushed:0,deleted:0,conflicts:0};try{
  const con=connection(uid),c=await client(con.credentials),calendar={url:con.selected.url},loaded=await loadRemote(uid,c,calendar);let maps=mappings(uid);
  for(const remote of loaded.remote){let map=maps.find(m=>m.remote_url===remote.url&&m.remote_key===remote.key&&m.uid===remote.uid);if(!map){const local=workspace(uid).data.events.find(e=>remote.uid===`${e.id}@flowday.${uid}`);if(local){save(uid,{...local,...remote.event},remote,'local');maps=mappings(uid);map=maps.find(m=>m.event_id===local.id);}else{pull(uid,remote,null);counts.imported++;maps=mappings(uid);continue;}}
   const local=workspace(uid).data.events.find(e=>e.id===map.event_id),base=JSON.parse(map.base_local),oldRemote=map.base_remote?JSON.parse(map.base_remote):null,localChanged=!sameEvent(local,base),remoteChanged=!sameEvent(remote.event,oldRemote);
   if(localChanged&&remoteChanged&&!sameEvent(local,remote.event)){markConflict(uid,map,local,remote);counts.conflicts++;continue;}
   if(remoteChanged){pull(uid,remote,map);counts.imported++;}
   else if(localChanged&&(!eventIds||eventIds.includes(map.event_id))){if(!local){markConflict(uid,map,local,remote);counts.conflicts++;continue;}const result=await push(uid,c,calendar,local,remote,map);counts.pushed++;const object=loaded.objects.find(v=>v.url===remote.url);if(object&&result.data){object.data=result.data;object.etag=result.etag;for(const entry of loaded.remote.filter(v=>v.url===remote.url)){entry.data=result.data;entry.etag=result.etag;}}}
   else if(sameEvent(local,remote.event)&&map.status==='conflict')save(uid,local,remote,map.source,map);
  }
  for(const map of maps){if(loaded.remote.some(r=>r.url===map.remote_url&&r.key===map.remote_key&&r.uid===map.uid))continue;const local=workspace(uid).data.events.find(e=>e.id===map.event_id);if(!local||local.deletedAt)continue;const base=JSON.parse(map.base_local);if(!sameEvent(local,base)){markConflict(uid,map,local,null);counts.conflicts++;}else{pull(uid,{url:map.remote_url,key:map.remote_key,uid:map.uid,event:null},map);counts.deleted++;}}
  for(const local of workspace(uid).data.events.filter(e=>!e.deletedAt&&!mappings(uid).some(m=>m.event_id===e.id)&&(!eventIds||eventIds.includes(e.id)))){await push(uid,c,calendar,local,null,null);counts.pushed++;}
  db.prepare('UPDATE calendar_connections SET last_sync=?,last_error=NULL WHERE user_id=?').run(now(),uid);return {version:workspace(uid).version,...counts};
 }catch(e){db.prepare("UPDATE calendar_connections SET last_error='CALDAV_SYNC_FAILED' WHERE user_id=?").run(uid);if(e instanceof ApiError)throw e;throw new ApiError(502,'CALDAV_SYNC_FAILED','Apple 日历同步失败');}finally{active.delete(uid);}}
 app.post('/api/v1/integrations/apple/sync',config,async req=>{object(req.body??{},{eventIds:v=>Array.isArray(v)&&v.length<=10000&&v.every(text)});return sync(req.uid,req.body?.eventIds);});
 app.post('/api/v1/integrations/apple/conflicts/:id/resolve',config,async req=>{object(req.body,{choice:v=>['local','remote'].includes(v),baseVersion:integer},['choice','baseVersion']);locked(req.uid);active.add(req.uid);try{const conflict=db.prepare('SELECT * FROM calendar_conflicts WHERE id=? AND user_id=? AND resolved=0').get(req.params.id,req.uid);if(!conflict)throw new ApiError(404,'NOT_FOUND','同步冲突不存在');const w=workspace(req.uid);if(w.version!==req.body.baseVersion)throw new ApiError(409,'VERSION_CONFLICT','工作区已变化',{currentVersion:w.version});const map=db.prepare('SELECT * FROM calendar_mappings WHERE id=?').get(conflict.mapping_id),con=connection(req.uid),c=await client(con.credentials),calendar={url:con.selected.url},loaded=await loadRemote(req.uid,c,calendar),remote=loaded.remote.find(r=>r.url===map.remote_url&&r.key===map.remote_key&&r.uid===map.uid);const expected=conflict.remote_data?JSON.parse(conflict.remote_data):null;if(!sameEvent(remote?.event??null,expected))throw new ApiError(409,'CALDAV_REMOTE_CHANGED','外部日程已变化，请重新同步');if(workspace(req.uid).version!==w.version)throw new ApiError(409,'VERSION_CONFLICT','工作区已变化',{currentVersion:workspace(req.uid).version});const local=w.data.events.find(e=>e.id===map.event_id);if(req.body.choice==='remote')pull(req.uid,remote??{url:map.remote_url,key:map.remote_key,uid:map.uid,event:null},map);else {check(local,'本地对象不存在');const resource=loaded.objects.find(o=>o.url===map.remote_url);await push(req.uid,c,calendar,local,remote??(resource?{...resource,key:map.remote_key,uid:map.uid,event:null}:null),map);}db.prepare('UPDATE calendar_conflicts SET resolved=1 WHERE id=?').run(conflict.id);audit(req.uid,'apple.resolve');return {version:workspace(req.uid).version,resolved:true};}finally{active.delete(req.uid);}});
 app.post('/api/v1/integrations/apple/disconnect',{preHandler:auth},async req=>{object(req.body??{},{keepLocal:v=>typeof v==='boolean'});locked(req.uid);return tx(()=>{if(req.body?.keepLocal===false){const w=workspace(req.uid),ids=new Set(mappings(req.uid).map(m=>m.event_id));for(const e of w.data.events)if(ids.has(e.id))e.deletedAt=new Date(now()).toISOString();cas(req.uid,w.version,w.data);}db.prepare('DELETE FROM calendar_mappings WHERE user_id=?').run(req.uid);db.prepare('DELETE FROM calendar_connections WHERE user_id=?').run(req.uid);audit(req.uid,'apple.disconnect');return {configured:false};});});
 const runWorker=async()=>{const interval=Math.max(60000,Number(env.CALDAV_SYNC_INTERVAL_MS??300000));for(const row of db.prepare('SELECT user_id FROM calendar_connections WHERE last_attempt IS NULL OR last_attempt<=?').all(now()-interval)){if(active.has(row.user_id))continue;await sync(row.user_id).catch(()=>{});}};
 return {runWorker};
}
