import {randomBytes,createHash,createHmac,createCipheriv,createDecipheriv,timingSafeEqual} from 'node:crypto';
import {ApiError,check,object} from './validation.js';
const hash=v=>createHash('sha256').update(v).digest('hex');
const text=v=>typeof v==='string'&&v.length>0&&v.length<=2000;
const escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function registerIntegrations({app,db,auth,env,now,tx,workspace,cas,audit,fetcher}){
 db.exec(`CREATE TABLE IF NOT EXISTS integrations(user_id TEXT PRIMARY KEY REFERENCES users(id),encrypted TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS reminder_actions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),reminder_id TEXT NOT NULL,action TEXT NOT NULL,minutes INTEGER,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS reminder_action_details(token_hash TEXT PRIMARY KEY REFERENCES reminder_actions(token_hash) ON DELETE CASCADE,details TEXT NOT NULL);`);
 const key=()=>{if(!/^[a-fA-F0-9]{64}$/.test(env.INTEGRATION_ENCRYPTION_KEY??''))throw new ApiError(503,'ENCRYPTION_NOT_CONFIGURED','集成加密密钥尚未配置');return Buffer.from(env.INTEGRATION_ENCRYPTION_KEY,'hex');};
 const seal=value=>{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64');};
 const config=uid=>{const row=db.prepare('SELECT encrypted FROM integrations WHERE user_id=?').get(uid);if(!row)return env.FEISHU_WEBHOOK_URL?{webhookUrl:env.FEISHU_WEBHOOK_URL,secret:env.FEISHU_WEBHOOK_SECRET}:null;const bytes=Buffer.from(row.encrypted,'base64'),decipher=createDecipheriv('aes-256-gcm',key(),bytes.subarray(0,12));decipher.setAuthTag(bytes.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString('utf8'));};
 const configured=uid=>!!db.prepare('SELECT user_id FROM integrations WHERE user_id=?').get(uid)||!!env.FEISHU_WEBHOOK_URL;
 const validateUrl=v=>{try{const u=new URL(v);return u.protocol==='https:'&&u.hostname==='open.feishu.cn'&&!u.username&&!u.password&&!u.search&&!u.hash&&/^\/open-apis\/bot\/v2\/hook\/[a-zA-Z0-9-]+$/.test(u.pathname);}catch{return false;}};
 app.get('/api/v1/integrations/feishu',{preHandler:auth},async req=>({configured:configured(req.uid)}));
 app.put('/api/v1/integrations/feishu',{preHandler:auth},async req=>{object(req.body,{webhookUrl:validateUrl,secret:v=>typeof v==='string'&&v.length<=256},['webhookUrl']);db.prepare('INSERT INTO integrations VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET encrypted=excluded.encrypted').run(req.uid,seal(req.body));audit(req.uid,'feishu.configure');return {configured:true};});
 app.post('/api/v1/integrations/feishu/disconnect',{preHandler:auth},async req=>{db.prepare('DELETE FROM integrations WHERE user_id=?').run(req.uid);return {configured:configured(req.uid)};});
 const send=async(uid,payload)=>{const c=config(uid);if(!c)throw new ApiError(503,'FEISHU_NOT_CONFIGURED','飞书提醒尚未配置');if(c.secret){const timestamp=Math.floor(now()/1000);payload={...payload,timestamp:String(timestamp),sign:createHmac('sha256',`${timestamp}\n${c.secret}`).digest('base64')};}const response=await fetcher(c.webhookUrl,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(10000),body:JSON.stringify(payload)});if(!response.ok)throw new ApiError(502,'FEISHU_DELIVERY_FAILED','飞书发送失败');const result=await response.json();if(result.code!==0&&result.StatusCode!==0)throw new ApiError(502,'FEISHU_DELIVERY_FAILED','飞书发送失败');};
 app.post('/api/v1/integrations/feishu/test',{preHandler:auth,config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async req=>{await send(req.uid,{msg_type:'text',content:{text:'FlowDay 测试提醒'}});return {delivered:true};});
 const issue=(uid,rid,action,minutes)=>{if(!env.ACTION_SIGNING_KEY||env.ACTION_SIGNING_KEY.length<24)throw new ApiError(503,'ACTION_SIGNING_NOT_CONFIGURED','提醒动作签名尚未配置');const nonce=randomBytes(32).toString('hex'),signature=createHmac('sha256',env.ACTION_SIGNING_KEY).update(nonce).digest('hex'),token=nonce+'.'+signature,expires=now()+30*60000;db.prepare('INSERT INTO reminder_actions VALUES(?,?,?,?,?,?,0)').run(hash(token),uid,rid,action,minutes??null,expires);if(action==='postpone'){const r=db.prepare('SELECT event_id FROM reminders WHERE id=? AND user_id=?').get(rid,uid),w=workspace(uid),event=w.data.events.find(e=>e.id===r.event_id&&!e.deletedAt);check(event&&Date.parse(event.start)>now(),'仅能延后未开始的有效日程');db.prepare('INSERT INTO reminder_action_details VALUES(?,?)').run(hash(token),JSON.stringify({baseVersion:w.version,eventId:event.id,start:event.start,end:event.end,newStart:new Date(Date.parse(event.start)+minutes*60000).toISOString(),newEnd:new Date(Date.parse(event.end)+minutes*60000).toISOString()}));}return {token,expiresAt:new Date(expires).toISOString(),...(env.PUBLIC_BASE_URL?{url:env.PUBLIC_BASE_URL.replace(/\/$/,'')+(action==='open'?'/reminder-detail?token=':'/reminder-action?token=')+token}:{})};};
 app.post('/api/v1/reminders/:id/actions',{preHandler:auth},async req=>{object(req.body,{action:v=>['ack','start','complete','snooze','postpone','open'].includes(v),minutes:v=>Number.isSafeInteger(v)&&v>=1&&v<=10080},['action']);check(!['snooze','postpone'].includes(req.body.action)||req.body.minutes!==undefined,'稍后提醒需要分钟数');if(!db.prepare('SELECT id FROM reminders WHERE id=? AND user_id=?').get(req.params.id,req.uid))throw new ApiError(404,'NOT_FOUND','提醒不存在');return issue(req.uid,req.params.id,req.body.action,req.body.minutes);});
 const execute=token=>tx(()=>{check(typeof token==='string'&&/^[a-f0-9]{64}\.[a-f0-9]{64}$/.test(token),'动作签名无效');const [nonce,sig]=token.split('.'),expected=createHmac('sha256',env.ACTION_SIGNING_KEY??'').update(nonce).digest();if(!timingSafeEqual(expected,Buffer.from(sig,'hex')))throw new ApiError(401,'INVALID_ACTION','动作签名无效');const action=db.prepare('SELECT * FROM reminder_actions WHERE token_hash=?').get(hash(token));if(!action||action.used||action.expires<=now())throw new ApiError(410,'ACTION_EXPIRED','提醒动作已使用或过期');const r=db.prepare('SELECT * FROM reminders WHERE id=? AND user_id=?').get(action.reminder_id,action.user_id);if(!r)throw new ApiError(404,'NOT_FOUND','提醒不存在');
  if(action.action==='ack')db.prepare('UPDATE reminders SET acknowledged=1 WHERE id=?').run(r.id);
  else if(action.action==='snooze')db.prepare('UPDATE reminders SET due=?,sent=0 WHERE id=?').run(now()+action.minutes*60000,r.id);
  else if(action.action==='postpone'){const detail=JSON.parse(db.prepare('SELECT details FROM reminder_action_details WHERE token_hash=?').get(hash(token)).details),w=workspace(action.user_id);const event=w.data.events.find(e=>e.id===detail.eventId&&!e.deletedAt);check(event,'日程不存在');if(event.start!==detail.start||event.end!==detail.end)throw new ApiError(409,'VERSION_CONFLICT','日程已变化，请重新打开提醒',{currentVersion:w.version});event.start=detail.newStart;event.end=detail.newEnd;cas(action.user_id,w.version,w.data);}
  else if(action.action==='open'){return {opened:true};}
  else {const w=workspace(action.user_id),task=w.data.tasks.find(v=>v.id===r.task_id&&!v.deletedAt);check(task,'提醒没有关联有效任务');task.status=action.action==='start'?'doing':'done';if(task.status==='done')task.completedAt=new Date(now()).toISOString();cas(action.user_id,w.version,w.data);}
  db.prepare('UPDATE reminder_actions SET used=1 WHERE token_hash=?').run(hash(token));audit(action.user_id,'reminder.'+action.action);return {executed:true,action:action.action};});
 app.post('/api/v1/reminder-actions',{config:{rateLimit:{max:20,timeWindow:'1 minute'}}},async req=>{object(req.body,{token:text},['token']);return execute(req.body.token);});
 app.get('/reminder-detail',async(req,reply)=>{const token=req.query.token;check(typeof token==='string'&&/^[a-f0-9]{64}\.[a-f0-9]{64}$/.test(token));const action=db.prepare("SELECT * FROM reminder_actions WHERE token_hash=? AND action='open'").get(hash(token));if(!action||action.used||action.expires<=now())throw new ApiError(410,'ACTION_EXPIRED','提醒动作已过期');const reminder=db.prepare('SELECT * FROM reminders WHERE id=? AND user_id=?').get(action.reminder_id,action.user_id);if(!reminder)throw new ApiError(404,'NOT_FOUND','提醒不存在');const w=workspace(action.user_id),event=w.data.events.find(e=>e.id===reminder.event_id),task=w.data.tasks.find(t=>t.id===reminder.task_id);return reply.header('Cache-Control','no-store').header('Referrer-Policy','no-referrer').header('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'").type('text/html').send(`<html lang="zh"><meta charset="utf-8"><h1>${escape(reminder.title)}</h1>${event?'<p>'+escape(event.start)+' — '+escape(event.end)+'</p>':''}${task?'<p>'+escape(task.title)+'</p>':''}</html>`);});
 app.get('/reminder-action',async(req,reply)=>{const token=req.query.token;check(typeof token==='string'&&/^[a-f0-9]{64}\.[a-f0-9]{64}$/.test(token));const row=db.prepare('SELECT action,expires,used FROM reminder_actions WHERE token_hash=?').get(hash(token));if(!row||row.used||row.expires<=now())throw new ApiError(410,'ACTION_EXPIRED','提醒动作已使用或过期');const details=db.prepare('SELECT details FROM reminder_action_details WHERE token_hash=?').get(hash(token));const preview=details?JSON.parse(details.details):null;reply.header('Cache-Control','no-store').header('Referrer-Policy','no-referrer').header('Content-Security-Policy',"default-src 'none'; form-action 'self'; frame-ancestors 'none'");return reply.type('text/html').send(`<html lang="zh"><meta charset="utf-8">${preview?'<p>'+escape(preview.start)+' — '+escape(preview.end)+' → '+escape(preview.newStart)+' — '+escape(preview.newEnd)+'</p>':''}<form method="post" action="/reminder-action"><input type="hidden" name="token" value="${escape(token)}"><button>确认${{ack:'已知晓',start:'开始',complete:'完成',snooze:'稍后提醒',postpone:'延后日程',open:'打开详情'}[row.action]}</button></form></html>`);});
 app.addContentTypeParser('application/x-www-form-urlencoded',{parseAs:'string'},(req,body,done)=>{done(null,Object.fromEntries(new URLSearchParams(body)));});
 app.post('/reminder-action',async(req,reply)=>{object(req.body,{token:text},['token']);execute(req.body.token);return reply.header('Cache-Control','no-store').type('text/html').send('<html lang="zh"><meta charset="utf-8">已完成</html>');});
 const deliver=async r=>{const w=workspace(r.user_id),event=w.data.events.find(e=>e.id===r.event_id),project=w.data.projects.find(p=>p.id===event?.projectId);const elements=[{tag:'div',text:{tag:'plain_text',content:[r.title,event?event.start:'',project?.title??''].filter(Boolean).join('\n')}}];if(env.PUBLIC_BASE_URL&&env.ACTION_SIGNING_KEY){const buttons=[['ack','已知晓'],['snooze','稍后5分钟'],['open','打开详情'],...(event&&Date.parse(event.start)>now()?[['postpone','延后10分钟']]:[]),...(r.task_id?[['start','开始'],['complete','完成']]:[])].map(([action,label])=>({tag:'button',text:{tag:'plain_text',content:label},url:issue(r.user_id,r.id,action,action==='snooze'?5:action==='postpone'?10:undefined).url}));elements.push({tag:'action',actions:buttons});}await send(r.user_id,{msg_type:'interactive',card:{header:{title:{tag:'plain_text',content:r.title}},elements}});};
 return {configured,deliver};
}
